//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisUrun
    {
        public int siparisUrunID { get; set; }
        public Nullable<int> adisyonNo { get; set; }
        public Nullable<int> urunID { get; set; }
        public Nullable<int> adet { get; set; }
    
        public virtual Adisyon Adisyon { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
